//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Core.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM 关系源元数据

[assembly: EdmRelationshipAttribute("InfosDBModel", "FK_Review_ToTable", "Info", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SecondHand.Models.Info), "Review", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SecondHand.Models.Review), true)]

#endregion

namespace SecondHand.Models
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class InfosDBEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“InfosDBEntities”部分中的连接字符串初始化新 InfosDBEntities 对象。
        /// </summary>
        public InfosDBEntities() : base("name=InfosDBEntities", "InfosDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 InfosDBEntities 对象。
        /// </summary>
        public InfosDBEntities(string connectionString) : base(connectionString, "InfosDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 InfosDBEntities 对象。
        /// </summary>
        public InfosDBEntities(EntityConnection connection) : base(connection, "InfosDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Info> Info
        {
            get
            {
                if ((_Info == null))
                {
                    _Info = base.CreateObjectSet<Info>("Info");
                }
                return _Info;
            }
        }
        private ObjectSet<Info> _Info;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Table> Table
        {
            get
            {
                if ((_Table == null))
                {
                    _Table = base.CreateObjectSet<Table>("Table");
                }
                return _Table;
            }
        }
        private ObjectSet<Table> _Table;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Review> Review
        {
            get
            {
                if ((_Review == null))
                {
                    _Review = base.CreateObjectSet<Review>("Review");
                }
                return _Review;
            }
        }
        private ObjectSet<Review> _Review;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 Info EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToInfo(Info info)
        {
            base.AddObject("Info", info);
        }
    
        /// <summary>
        /// 用于向 Table EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToTable(Table table)
        {
            base.AddObject("Table", table);
        }
    
        /// <summary>
        /// 用于向 Review EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToReview(Review review)
        {
            base.AddObject("Review", review);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InfosDBModel", Name="Info")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Info : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Info 对象。
        /// </summary>
        /// <param name="id">Id 属性的初始值。</param>
        /// <param name="username">Username 属性的初始值。</param>
        /// <param name="tel">Tel 属性的初始值。</param>
        /// <param name="type">Type 属性的初始值。</param>
        /// <param name="product">Product 属性的初始值。</param>
        /// <param name="price">Price 属性的初始值。</param>
        /// <param name="status">Status 属性的初始值。</param>
        /// <param name="password">Password 属性的初始值。</param>
        /// <param name="tradingstatus">Tradingstatus 属性的初始值。</param>
        public static Info CreateInfo(global::System.Int32 id, global::System.String username, global::System.String tel, global::System.String type, global::System.String product, global::System.String price, global::System.String status, global::System.String password, global::System.String tradingstatus)
        {
            Info info = new Info();
            info.Id = id;
            info.Username = username;
            info.Tel = tel;
            info.Type = type;
            info.Product = product;
            info.Price = price;
            info.Status = status;
            info.Password = password;
            info.Tradingstatus = tradingstatus;
            return info;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, false, "Username");
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Tel
        {
            get
            {
                return _Tel;
            }
            set
            {
                OnTelChanging(value);
                ReportPropertyChanging("Tel");
                _Tel = StructuralObject.SetValidValue(value, false, "Tel");
                ReportPropertyChanged("Tel");
                OnTelChanged();
            }
        }
        private global::System.String _Tel;
        partial void OnTelChanging(global::System.String value);
        partial void OnTelChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, false, "Type");
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Product
        {
            get
            {
                return _Product;
            }
            set
            {
                OnProductChanging(value);
                ReportPropertyChanging("Product");
                _Product = StructuralObject.SetValidValue(value, false, "Product");
                ReportPropertyChanged("Product");
                OnProductChanged();
            }
        }
        private global::System.String _Product;
        partial void OnProductChanging(global::System.String value);
        partial void OnProductChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Detail
        {
            get
            {
                return _Detail;
            }
            set
            {
                OnDetailChanging(value);
                ReportPropertyChanging("Detail");
                _Detail = StructuralObject.SetValidValue(value, true, "Detail");
                ReportPropertyChanged("Detail");
                OnDetailChanged();
            }
        }
        private global::System.String _Detail;
        partial void OnDetailChanging(global::System.String value);
        partial void OnDetailChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value, false, "Price");
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private global::System.String _Price;
        partial void OnPriceChanging(global::System.String value);
        partial void OnPriceChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, false, "Status");
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Pic
        {
            get
            {
                return _Pic;
            }
            set
            {
                OnPicChanging(value);
                ReportPropertyChanging("Pic");
                _Pic = StructuralObject.SetValidValue(value, true, "Pic");
                ReportPropertyChanged("Pic");
                OnPicChanged();
            }
        }
        private global::System.String _Pic;
        partial void OnPicChanging(global::System.String value);
        partial void OnPicChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false, "Password");
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Tradingstatus
        {
            get
            {
                return _Tradingstatus;
            }
            set
            {
                OnTradingstatusChanging(value);
                ReportPropertyChanging("Tradingstatus");
                _Tradingstatus = StructuralObject.SetValidValue(value, false, "Tradingstatus");
                ReportPropertyChanged("Tradingstatus");
                OnTradingstatusChanged();
            }
        }
        private global::System.String _Tradingstatus;
        partial void OnTradingstatusChanging(global::System.String value);
        partial void OnTradingstatusChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Infotime
        {
            get
            {
                return _Infotime;
            }
            set
            {
                OnInfotimeChanging(value);
                ReportPropertyChanging("Infotime");
                _Infotime = StructuralObject.SetValidValue(value, "Infotime");
                ReportPropertyChanged("Infotime");
                OnInfotimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _Infotime;
        partial void OnInfotimeChanging(Nullable<global::System.DateTime> value);
        partial void OnInfotimeChanged();

        #endregion

        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InfosDBModel", "FK_Review_ToTable", "Review")]
        public EntityCollection<Review> Review
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Review>("InfosDBModel.FK_Review_ToTable", "Review");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Review>("InfosDBModel.FK_Review_ToTable", "Review", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InfosDBModel", Name="Review")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Review : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Review 对象。
        /// </summary>
        /// <param name="reid">Reid 属性的初始值。</param>
        public static Review CreateReview(global::System.Int32 reid)
        {
            Review review = new Review();
            review.Reid = reid;
            return review;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Reid
        {
            get
            {
                return _Reid;
            }
            set
            {
                if (_Reid != value)
                {
                    OnReidChanging(value);
                    ReportPropertyChanging("Reid");
                    _Reid = StructuralObject.SetValidValue(value, "Reid");
                    ReportPropertyChanged("Reid");
                    OnReidChanged();
                }
            }
        }
        private global::System.Int32 _Reid;
        partial void OnReidChanging(global::System.Int32 value);
        partial void OnReidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Id
        {
            get
            {
                return _Id;
            }
            set
            {
                OnIdChanging(value);
                ReportPropertyChanging("Id");
                _Id = StructuralObject.SetValidValue(value, "Id");
                ReportPropertyChanged("Id");
                OnIdChanged();
            }
        }
        private Nullable<global::System.Int32> _Id;
        partial void OnIdChanging(Nullable<global::System.Int32> value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Upid
        {
            get
            {
                return _Upid;
            }
            set
            {
                OnUpidChanging(value);
                ReportPropertyChanging("Upid");
                _Upid = StructuralObject.SetValidValue(value, "Upid");
                ReportPropertyChanged("Upid");
                OnUpidChanged();
            }
        }
        private Nullable<global::System.Int32> _Upid;
        partial void OnUpidChanging(Nullable<global::System.Int32> value);
        partial void OnUpidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Rename
        {
            get
            {
                return _Rename;
            }
            set
            {
                OnRenameChanging(value);
                ReportPropertyChanging("Rename");
                _Rename = StructuralObject.SetValidValue(value, true, "Rename");
                ReportPropertyChanged("Rename");
                OnRenameChanged();
            }
        }
        private global::System.String _Rename;
        partial void OnRenameChanging(global::System.String value);
        partial void OnRenameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Content
        {
            get
            {
                return _Content;
            }
            set
            {
                OnContentChanging(value);
                ReportPropertyChanging("Content");
                _Content = StructuralObject.SetValidValue(value, true, "Content");
                ReportPropertyChanged("Content");
                OnContentChanged();
            }
        }
        private global::System.String _Content;
        partial void OnContentChanging(global::System.String value);
        partial void OnContentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Retime
        {
            get
            {
                return _Retime;
            }
            set
            {
                OnRetimeChanging(value);
                ReportPropertyChanging("Retime");
                _Retime = StructuralObject.SetValidValue(value, "Retime");
                ReportPropertyChanged("Retime");
                OnRetimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _Retime;
        partial void OnRetimeChanging(Nullable<global::System.DateTime> value);
        partial void OnRetimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Replyname
        {
            get
            {
                return _Replyname;
            }
            set
            {
                OnReplynameChanging(value);
                ReportPropertyChanging("Replyname");
                _Replyname = StructuralObject.SetValidValue(value, true, "Replyname");
                ReportPropertyChanged("Replyname");
                OnReplynameChanged();
            }
        }
        private global::System.String _Replyname;
        partial void OnReplynameChanging(global::System.String value);
        partial void OnReplynameChanged();

        #endregion

        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("InfosDBModel", "FK_Review_ToTable", "Info")]
        public Info Info
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Info>("InfosDBModel.FK_Review_ToTable", "Info").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Info>("InfosDBModel.FK_Review_ToTable", "Info").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Info> InfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Info>("InfosDBModel.FK_Review_ToTable", "Info");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Info>("InfosDBModel.FK_Review_ToTable", "Info", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="InfosDBModel", Name="Table")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Table : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Table 对象。
        /// </summary>
        /// <param name="time">Time 属性的初始值。</param>
        /// <param name="type">Type 属性的初始值。</param>
        /// <param name="product">Product 属性的初始值。</param>
        /// <param name="status">Status 属性的初始值。</param>
        /// <param name="id">Id 属性的初始值。</param>
        /// <param name="uname">Uname 属性的初始值。</param>
        public static Table CreateTable(global::System.DateTime time, global::System.String type, global::System.String product, global::System.String status, global::System.Int32 id, global::System.String uname)
        {
            Table table = new Table();
            table.Time = time;
            table.Type = type;
            table.Product = product;
            table.Status = status;
            table.Id = id;
            table.Uname = uname;
            return table;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Time
        {
            get
            {
                return _Time;
            }
            set
            {
                OnTimeChanging(value);
                ReportPropertyChanging("Time");
                _Time = StructuralObject.SetValidValue(value, "Time");
                ReportPropertyChanged("Time");
                OnTimeChanged();
            }
        }
        private global::System.DateTime _Time;
        partial void OnTimeChanging(global::System.DateTime value);
        partial void OnTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, false, "Type");
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Product
        {
            get
            {
                return _Product;
            }
            set
            {
                OnProductChanging(value);
                ReportPropertyChanging("Product");
                _Product = StructuralObject.SetValidValue(value, false, "Product");
                ReportPropertyChanged("Product");
                OnProductChanged();
            }
        }
        private global::System.String _Product;
        partial void OnProductChanging(global::System.String value);
        partial void OnProductChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Pic
        {
            get
            {
                return _Pic;
            }
            set
            {
                OnPicChanging(value);
                ReportPropertyChanging("Pic");
                _Pic = StructuralObject.SetValidValue(value, true, "Pic");
                ReportPropertyChanged("Pic");
                OnPicChanged();
            }
        }
        private global::System.String _Pic;
        partial void OnPicChanging(global::System.String value);
        partial void OnPicChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, false, "Status");
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Uname
        {
            get
            {
                return _Uname;
            }
            set
            {
                OnUnameChanging(value);
                ReportPropertyChanging("Uname");
                _Uname = StructuralObject.SetValidValue(value, false, "Uname");
                ReportPropertyChanged("Uname");
                OnUnameChanged();
            }
        }
        private global::System.String _Uname;
        partial void OnUnameChanging(global::System.String value);
        partial void OnUnameChanged();

        #endregion

    }

    #endregion

}
